---
language: node_js
node_js:
  - 8.10

sudo: false

dist: trusty

cache:
  npm: true

install:
  - npm install -g npm@5.10
  - npm ci --no-audit --no-color

script:
  - npm run lint

notifications:
  email:
    on_success: 'change'
    on_failure: 'change'
